import "./globals.css";

export const metadata = {
  title: "Visions to Visuals | Website Design and Development",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
