import "./globals.css";
import {font} from "next/font";

const gilroyBold = font({
  src: '/fonts/G-bold.ttf',
  fontDisplay: 'swap',
});

const gilroyMedium = font({
  src: '/fonts/G-medium.ttf',
  fontDisplay: 'swap',
});

const gilroyRegular = font({
  src: '/fonts/G-regular.ttf',
  fontDisplay: 'swap',
});

const gilroySemi = font({
  src: '/fonts/G-semi.ttf',
  fontDisplay: 'swap',
});

export const metadata = {
  title: "Visions to Visuals | Website Design and Development",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${gilroyBold.className} ${gilroyMedium.className} ${gilroyRegular.className} ${gilroySemi.className}`}>
      <body>{children}</body>
    </html>
  );
}
